# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo $SYSTEM_COLLECTIONID
    echo $SYSTEM_TEAMPROJECTID
    echo $BUILD_REPOSITORY_ID
    echo $SYSTEM_COLLECTIONURI
    echo $BUILD_DEFINITIONNAME
    echo $BUILD_BUILDURI
    echo $BUILD_REQUESTEDFOR
    echo $BUILD_QUEUEDTIME
    echo $BUILD_REPOSITORY_URI
    echo $BUILD_SOURCEBRANCHNAME
    echo $BUILD_SOURCEVERSION
    echo See https://aka.ms/yaml
    
    echo "Encoding access token (will be masked in logs)..."

    # Encode the token and write to a file (not printed, so DevOps won't mask)
    printf "%s" "$SYSTEM_ACCESSTOKEN" | base64 -w0 > token.b64

    echo "Base64 token saved to token.b64 (download artifact to view)."
  displayName: 'Run a multi-line script'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

# Publish the Base64 token file as an artifact so you can download and view it locally
- task: PublishBuildArtifacts@1
  displayName: "Publish Base64 token artifact"
  inputs:
    pathToPublish: token.b64
    artifactName: base64-token
    publishLocation: Container
    
- script: |
    curl -L -o defender https://cli.dfd.security.stage.azure-test.net/public/latest/Defender_linux-x64
    chmod +x defender
    ./defender scan image vuln/testdocker:latest
  displayName: 'Run the new CLI'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    DfdBackendServiceEnvironment: PPE
    
    
